name:                websockets-simple-extra
version:             0.0.0
github:              "athanclark/websockets-simple-extra"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2019 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/websockets-simple-extra#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- websockets-simple

library:
  source-dirs: src
